# Configuration file in YAML format
#
#
# Processing configs
process:
  
  # verbose mode (INFO/DEBUG)
  verbose: INFO

# campaign specifications
campaign:

  author: 'AUTHOR NAME'
  contact: 'AUTHOR CONTACT DETAILS'
  
  # solution (ULT/RAP/FIN)
  sol_id: FIN
  
  # Campaign/Project specification
  camp_id: TST
  
  # Combination name/abbreviation (3 characters)
  cmb_name: IGS

  # Combination version/solution identifier (0 to 9)
  vid : 0

  # root directory for AC submissions
  subm_rootdir: ./ac_subm

  # root directory for saving the products
  prod_rootdir: ./products

  # path to satellite metadata file
  sat_metadata_file: ./metadata/igs_satellite_metadata.snx

  # Earth orientation parameters (EOP) source format
  # (IERS_EOP14_C04/IERS_EOP_rapid/IGS_ERP2)
  eop_format: IERS_EOP_rapid

  # path to the EOP data
  eop_file: ./eop/finals.data_2024

  # Root directory for reference frame combination summary files
  # Needed for reference frame alignment
  rf_rootdir: ./sinex

  # Reference frame summary file name identifier
  rf_name: IGS0OPSSNX

  # nanu summary file
  nanu_sumfile: ./metadata/nanus_sum.2024

  ac_acronyms:
      COD: "Center for Orbit Determination in Europe (CODE)"
      EMR: "Natural Resources Canada (NRCan)"
      ESA: "European Space Agency"
      GFZ: "GeoForschungsZentrum Potsdam"
      GRG: "Centre National d'Etudes Spatiales (CNES/CLS)"
      JGX: "Geospatial Information Authority of Japan (GSI) and the Japan Aerospace Exploration Agency (JAXA)"
      JPL: "Jet Propulsion Laboratory"
      MIT: "Massachusetts Institute of Technology"
      NGS: "NOAA/National Geodetic Survey"
      SIO: "Scripps Institution of Oceanography (SIO)"
      IGF: "IGS final operational orbit product"
      IGL: "IGS experimental final GLONASS solution"

# Orbit combination configs
orbits:

  # Analysis center contributions
  ac_contribs:

    # weighted centers:
    weighted:
      systems:
        COD: [G,R,E]
        EMR: [G]
        ESA: [G,R,E]
        GFZ: [G,R,E]
        GRG: [G,R,E]
        JPL: [G,E]
        JGX: [G,R,E]
        MIT: [G,E]
        NGS: [G]
        SIO: [G]
      prns:
      svns:

    # unweighted centers (for comparison only)
    unweighted:
      systems:
        IGF: [G]
        IGL: [R]
      prns:
      svns:

    # excluded centers
    excluded:
      systems:
      prns:
      svns:

  # sampling rate (integer in seconds)
  sampling: 300

  # center weighting method (global/by_constellation/by_block/by_sat)
  cen_wht_method: by_constellation

  # satellite weighting method (RMS_L1)
  sat_wht_method: RMS_L1

  # Transform orbits to a same reference frame?
  # [Translations,Rotations,Scale]
  rf_align: [False,True,False]

  # UT1 differences applied as Z rotations
  # The ERP a priori and observed files for any center listed below must be
  # presented at rf_rootdir specified above with the long filename formats
  # {CEN}{V}{SOL}APR_{YYYYDDDHHMM}_{LEN}_{SMP}_ERP.ERP and
  # {CEN}{V}{SOL}OBS_{YYYYDDDHHMM}_{LEN}_{SMP}_ERP.ERP
  ut1_rot: []

  # remove DV maneuvering satellites
  rm_dv: True

  # exception for removing DV maneuvering satellites
  no_rm_dv: [COD]

  # outlier removal (assess) settings
  assess:

    # satellite rms test (auto/manual/strict)
    sat_rms_tst: auto

    # satellite rms test for unweighted centers (auto/manual/strict)
    # Note: depending on how bad the unweighted centers are, having 
    # sat_rms_tst_unweighted on could result in long running time
    # (e.g. if all the satellite solutions for an unweighted center
    # are very bad, which means at least 5 iterations for removing
    # the top five sats, assuming max_high_satrms is 5)
    #sat_rms_tst_unweighted : auto

    # coefficient for auto satellite rms test
    coef_sat: 470.0

    # threshold for manual satellite rms test for each satellite system (mm)
    thresh_sat:
      G: 15.0
      R: 25.0
      E: 15.0
      C: 50.0
      J: 100.0

    # maximum number of outlier satellite rms for a center in order to keep
    # being weighted
    max_high_satrms: 5

    # transformation parameters test (auto/manual/strict)
    trn_tst: strict

    # manual transformation thresholds for translation (mm), rotation (mas)
    # and scale (ppb)
    thresh_trn: [null,0.3,null]

    # test for minimum number of centers for each satellite (strict/eased)
    numcen_tst: eased

    # minimum number of centers for each satellite
    min_numcen: 1

    # maximum number of iterations for outlier removal
    max_iter: 100

  # SP3 header information
  sp3_header:

    # coordinate system
    coord_sys: IGS20

    # information to put into the comments

    # combination type
    cmb_type: FINAL

    # clock source
    clk_src: CMB

    # antex file
    antex: IGS20_2317

    # ocean tide model
    oload: FES2014b
